version: '3.4'
services:
  netbox:
    ports:
    - 9447:8080
    volumes:
    - /volume3/docker/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /volume3/docker/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  netbox-housekeeping:
    volumes:
    - /volume3/docker/netbox:/etc/netbox/config:z,ro
    - netbox-media-files:/opt/netbox/netbox/media:z,rw
    - netbox-reports-files:/opt/netbox/netbox/reports:z,rw
    - netbox-scripts-files:/opt/netbox/netbox/scripts:z,rw
  environment:
    SKIP_SUPERUSER: "false"
    # SUPERUSER_API_TOKEN: ""
    SUPERUSER_EMAIL: "admin@ventura.contact"
    SUPERUSER_NAME: "w0rkb3nch"
    SUPERUSER_PASSWORD: "@s$*t*POy8W9Z713"
